vim.keymap.set("n", "<leader>e", ":NvimTreeToggle<CR>", { desc = "Alternar NvimTree" })
vim.keymap.set("n", "<leader>ff", "<cmd>Telescope find_files<CR>", { desc = "Procurar Arquivos" })
vim.keymap.set("n", "<leader>fg", "<cmd>Telescope live_grep<CR>", { desc = "Busca Global (Live Grep)" })
vim.keymap.set("n", "<leader>fb", "<cmd>Telescope buffers<CR>", { desc = "Procurar Buffers" })
vim.keymap.set("n", "<leader>fh", "<cmd>Telescope help_tags<CR>", { desc = "Tags de Ajuda" })
vim.keymap.set("n", "<leader>jb", ":JavaBuildBuildWorkspace<CR>", { desc = "Java Build" })
vim.keymap.set("n", "<leader>jr", ":JavaRunnerRunMain<CR>", { desc = "Java Run" })
vim.keymap.set("n", "<leader>jt", ":JavaTestRunCurrentClass<CR>", { desc = "Java Test" })
vim.keymap.set("n", "<leader>jd", ":JavaDapConfig<CR>", { desc = "Java DAP" })
vim.keymap.set("n", "<C-h>", "<C-w>h", { desc = "Mover para esquerda" })
vim.keymap.set("n", "<C-j>", "<C-w>j", { desc = "Mover para baixo" })
vim.keymap.set("n", "<C-k>", "<C-w>k", { desc = "Mover para cima" })
vim.keymap.set("n", "<C-l>", "<C-w>l", { desc = "Mover para direita" })

-- DAP Keymaps
vim.keymap.set("n", "<F5>", function() require("dap").continue() end, { desc = "Debug: Continuar" })
vim.keymap.set("n", "<F10>", function() require("dap").step_over() end, { desc = "Debug: Pular (Step Over)" })
vim.keymap.set("n", "<F11>", function() require("dap").step_into() end, { desc = "Debug: Entrar (Step Into)" })
vim.keymap.set("n", "<F12>", function() require("dap").step_out() end, { desc = "Debug: Sair (Step Out)" })
vim.keymap.set("n", "<leader>db", function() require("dap").toggle_breakpoint() end, { desc = "Debug: Alternar Breakpoint" })
vim.keymap.set("n", "<leader>du", function() require("dapui").toggle() end, { desc = "Debug: Alternar Interface" })
